// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: cmd/htnwallet/daemon/pb/htnwalletd.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{0}
}

type GetBalanceResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Available       uint64                 `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Pending         uint64                 `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
	AddressBalances []*AddressBalances     `protobuf:"bytes,3,rep,name=addressBalances,proto3" json:"addressBalances,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{1}
}

func (x *GetBalanceResponse) GetAvailable() uint64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *GetBalanceResponse) GetPending() uint64 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *GetBalanceResponse) GetAddressBalances() []*AddressBalances {
	if x != nil {
		return x.AddressBalances
	}
	return nil
}

type AddressBalances struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Available     uint64                 `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	Pending       uint64                 `protobuf:"varint,3,opt,name=pending,proto3" json:"pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressBalances) Reset() {
	*x = AddressBalances{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressBalances) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressBalances) ProtoMessage() {}

func (x *AddressBalances) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressBalances.ProtoReflect.Descriptor instead.
func (*AddressBalances) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{2}
}

func (x *AddressBalances) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddressBalances) GetAvailable() uint64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *AddressBalances) GetPending() uint64 {
	if x != nil {
		return x.Pending
	}
	return 0
}

type CreateUnsignedTransactionsRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Address                  string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount                   uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	From                     []string               `protobuf:"bytes,3,rep,name=from,proto3" json:"from,omitempty"`
	UseExistingChangeAddress bool                   `protobuf:"varint,4,opt,name=useExistingChangeAddress,proto3" json:"useExistingChangeAddress,omitempty"`
	IsSendAll                bool                   `protobuf:"varint,5,opt,name=isSendAll,proto3" json:"isSendAll,omitempty"`
	Payload                  []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Limit                    *string                `protobuf:"bytes,7,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CreateUnsignedTransactionsRequest) Reset() {
	*x = CreateUnsignedTransactionsRequest{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUnsignedTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUnsignedTransactionsRequest) ProtoMessage() {}

func (x *CreateUnsignedTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUnsignedTransactionsRequest.ProtoReflect.Descriptor instead.
func (*CreateUnsignedTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUnsignedTransactionsRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateUnsignedTransactionsRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateUnsignedTransactionsRequest) GetFrom() []string {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *CreateUnsignedTransactionsRequest) GetUseExistingChangeAddress() bool {
	if x != nil {
		return x.UseExistingChangeAddress
	}
	return false
}

func (x *CreateUnsignedTransactionsRequest) GetIsSendAll() bool {
	if x != nil {
		return x.IsSendAll
	}
	return false
}

func (x *CreateUnsignedTransactionsRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CreateUnsignedTransactionsRequest) GetLimit() string {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return ""
}

type CreateUnsignedTransactionsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UnsignedTransactions [][]byte               `protobuf:"bytes,1,rep,name=unsignedTransactions,proto3" json:"unsignedTransactions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateUnsignedTransactionsResponse) Reset() {
	*x = CreateUnsignedTransactionsResponse{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUnsignedTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUnsignedTransactionsResponse) ProtoMessage() {}

func (x *CreateUnsignedTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUnsignedTransactionsResponse.ProtoReflect.Descriptor instead.
func (*CreateUnsignedTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUnsignedTransactionsResponse) GetUnsignedTransactions() [][]byte {
	if x != nil {
		return x.UnsignedTransactions
	}
	return nil
}

type CreateUnsignedCompoundTransactionRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Address                  string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	From                     []string               `protobuf:"bytes,2,rep,name=from,proto3" json:"from,omitempty"`
	UseExistingChangeAddress bool                   `protobuf:"varint,3,opt,name=useExistingChangeAddress,proto3" json:"useExistingChangeAddress,omitempty"`
	Limit                    *string                `protobuf:"bytes,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CreateUnsignedCompoundTransactionRequest) Reset() {
	*x = CreateUnsignedCompoundTransactionRequest{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUnsignedCompoundTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUnsignedCompoundTransactionRequest) ProtoMessage() {}

func (x *CreateUnsignedCompoundTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUnsignedCompoundTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateUnsignedCompoundTransactionRequest) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUnsignedCompoundTransactionRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateUnsignedCompoundTransactionRequest) GetFrom() []string {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *CreateUnsignedCompoundTransactionRequest) GetUseExistingChangeAddress() bool {
	if x != nil {
		return x.UseExistingChangeAddress
	}
	return false
}

func (x *CreateUnsignedCompoundTransactionRequest) GetLimit() string {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return ""
}

type CreateUnsignedCompoundTransactionResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UnsignedTransactions [][]byte               `protobuf:"bytes,1,rep,name=unsignedTransactions,proto3" json:"unsignedTransactions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateUnsignedCompoundTransactionResponse) Reset() {
	*x = CreateUnsignedCompoundTransactionResponse{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUnsignedCompoundTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUnsignedCompoundTransactionResponse) ProtoMessage() {}

func (x *CreateUnsignedCompoundTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUnsignedCompoundTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateUnsignedCompoundTransactionResponse) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{6}
}

func (x *CreateUnsignedCompoundTransactionResponse) GetUnsignedTransactions() [][]byte {
	if x != nil {
		return x.UnsignedTransactions
	}
	return nil
}

type ShowAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowAddressesRequest) Reset() {
	*x = ShowAddressesRequest{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowAddressesRequest) ProtoMessage() {}

func (x *ShowAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowAddressesRequest.ProtoReflect.Descriptor instead.
func (*ShowAddressesRequest) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{7}
}

type ShowAddressesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []string               `protobuf:"bytes,1,rep,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowAddressesResponse) Reset() {
	*x = ShowAddressesResponse{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowAddressesResponse) ProtoMessage() {}

func (x *ShowAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowAddressesResponse.ProtoReflect.Descriptor instead.
func (*ShowAddressesResponse) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{8}
}

func (x *ShowAddressesResponse) GetAddress() []string {
	if x != nil {
		return x.Address
	}
	return nil
}

type NewAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewAddressRequest) Reset() {
	*x = NewAddressRequest{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAddressRequest) ProtoMessage() {}

func (x *NewAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAddressRequest.ProtoReflect.Descriptor instead.
func (*NewAddressRequest) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{9}
}

type NewAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewAddressResponse) Reset() {
	*x = NewAddressResponse{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAddressResponse) ProtoMessage() {}

func (x *NewAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAddressResponse.ProtoReflect.Descriptor instead.
func (*NewAddressResponse) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{10}
}

func (x *NewAddressResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type BroadcastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDomain      bool                   `protobuf:"varint,1,opt,name=isDomain,proto3" json:"isDomain,omitempty"`
	Transactions  [][]byte               `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	AllowOrphan   bool                   `protobuf:"varint,3,opt,name=allowOrphan,proto3" json:"allowOrphan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{11}
}

func (x *BroadcastRequest) GetIsDomain() bool {
	if x != nil {
		return x.IsDomain
	}
	return false
}

func (x *BroadcastRequest) GetTransactions() [][]byte {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *BroadcastRequest) GetAllowOrphan() bool {
	if x != nil {
		return x.AllowOrphan
	}
	return false
}

type BroadcastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxIDs         []string               `protobuf:"bytes,1,rep,name=txIDs,proto3" json:"txIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastResponse) Reset() {
	*x = BroadcastResponse{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastResponse) ProtoMessage() {}

func (x *BroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastResponse.ProtoReflect.Descriptor instead.
func (*BroadcastResponse) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{12}
}

func (x *BroadcastResponse) GetTxIDs() []string {
	if x != nil {
		return x.TxIDs
	}
	return nil
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{13}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{14}
}

type Outpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outpoint) Reset() {
	*x = Outpoint{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outpoint) ProtoMessage() {}

func (x *Outpoint) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outpoint.ProtoReflect.Descriptor instead.
func (*Outpoint) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{15}
}

func (x *Outpoint) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Outpoint) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type UtxosByAddressesEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Outpoint      *Outpoint              `protobuf:"bytes,2,opt,name=outpoint,proto3" json:"outpoint,omitempty"`
	UtxoEntry     *UtxoEntry             `protobuf:"bytes,3,opt,name=utxoEntry,proto3" json:"utxoEntry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UtxosByAddressesEntry) Reset() {
	*x = UtxosByAddressesEntry{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtxosByAddressesEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtxosByAddressesEntry) ProtoMessage() {}

func (x *UtxosByAddressesEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtxosByAddressesEntry.ProtoReflect.Descriptor instead.
func (*UtxosByAddressesEntry) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{16}
}

func (x *UtxosByAddressesEntry) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UtxosByAddressesEntry) GetOutpoint() *Outpoint {
	if x != nil {
		return x.Outpoint
	}
	return nil
}

func (x *UtxosByAddressesEntry) GetUtxoEntry() *UtxoEntry {
	if x != nil {
		return x.UtxoEntry
	}
	return nil
}

type ScriptPublicKey struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ScriptPublicKey string                 `protobuf:"bytes,2,opt,name=scriptPublicKey,proto3" json:"scriptPublicKey,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScriptPublicKey) Reset() {
	*x = ScriptPublicKey{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptPublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptPublicKey) ProtoMessage() {}

func (x *ScriptPublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptPublicKey.ProtoReflect.Descriptor instead.
func (*ScriptPublicKey) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{17}
}

func (x *ScriptPublicKey) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ScriptPublicKey) GetScriptPublicKey() string {
	if x != nil {
		return x.ScriptPublicKey
	}
	return ""
}

type UtxoEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Amount          uint64                 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	ScriptPublicKey *ScriptPublicKey       `protobuf:"bytes,2,opt,name=scriptPublicKey,proto3" json:"scriptPublicKey,omitempty"`
	BlockDaaScore   uint64                 `protobuf:"varint,3,opt,name=blockDaaScore,proto3" json:"blockDaaScore,omitempty"`
	IsCoinbase      bool                   `protobuf:"varint,4,opt,name=isCoinbase,proto3" json:"isCoinbase,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UtxoEntry) Reset() {
	*x = UtxoEntry{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtxoEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtxoEntry) ProtoMessage() {}

func (x *UtxoEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtxoEntry.ProtoReflect.Descriptor instead.
func (*UtxoEntry) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{18}
}

func (x *UtxoEntry) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UtxoEntry) GetScriptPublicKey() *ScriptPublicKey {
	if x != nil {
		return x.ScriptPublicKey
	}
	return nil
}

func (x *UtxoEntry) GetBlockDaaScore() uint64 {
	if x != nil {
		return x.BlockDaaScore
	}
	return 0
}

func (x *UtxoEntry) GetIsCoinbase() bool {
	if x != nil {
		return x.IsCoinbase
	}
	return false
}

type GetExternalSpendableUTXOsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExternalSpendableUTXOsRequest) Reset() {
	*x = GetExternalSpendableUTXOsRequest{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExternalSpendableUTXOsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExternalSpendableUTXOsRequest) ProtoMessage() {}

func (x *GetExternalSpendableUTXOsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExternalSpendableUTXOsRequest.ProtoReflect.Descriptor instead.
func (*GetExternalSpendableUTXOsRequest) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{19}
}

func (x *GetExternalSpendableUTXOsRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetExternalSpendableUTXOsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Entries       []*UtxosByAddressesEntry `protobuf:"bytes,1,rep,name=Entries,proto3" json:"Entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExternalSpendableUTXOsResponse) Reset() {
	*x = GetExternalSpendableUTXOsResponse{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExternalSpendableUTXOsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExternalSpendableUTXOsResponse) ProtoMessage() {}

func (x *GetExternalSpendableUTXOsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExternalSpendableUTXOsResponse.ProtoReflect.Descriptor instead.
func (*GetExternalSpendableUTXOsResponse) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{20}
}

func (x *GetExternalSpendableUTXOsResponse) GetEntries() []*UtxosByAddressesEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Since SendRequest contains a password - this command should only be used on a trusted or secure connection
type SendRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ToAddress                string                 `protobuf:"bytes,1,opt,name=toAddress,proto3" json:"toAddress,omitempty"`
	Amount                   uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Password                 string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	From                     []string               `protobuf:"bytes,4,rep,name=from,proto3" json:"from,omitempty"`
	UseExistingChangeAddress bool                   `protobuf:"varint,5,opt,name=useExistingChangeAddress,proto3" json:"useExistingChangeAddress,omitempty"`
	IsSendAll                bool                   `protobuf:"varint,6,opt,name=isSendAll,proto3" json:"isSendAll,omitempty"`
	Limit                    *string                `protobuf:"bytes,7,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{21}
}

func (x *SendRequest) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *SendRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SendRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SendRequest) GetFrom() []string {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *SendRequest) GetUseExistingChangeAddress() bool {
	if x != nil {
		return x.UseExistingChangeAddress
	}
	return false
}

func (x *SendRequest) GetIsSendAll() bool {
	if x != nil {
		return x.IsSendAll
	}
	return false
}

func (x *SendRequest) GetLimit() string {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return ""
}

type SendResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TxIDs              []string               `protobuf:"bytes,1,rep,name=txIDs,proto3" json:"txIDs,omitempty"`
	SignedTransactions [][]byte               `protobuf:"bytes,2,rep,name=signedTransactions,proto3" json:"signedTransactions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{22}
}

func (x *SendResponse) GetTxIDs() []string {
	if x != nil {
		return x.TxIDs
	}
	return nil
}

func (x *SendResponse) GetSignedTransactions() [][]byte {
	if x != nil {
		return x.SignedTransactions
	}
	return nil
}

// Since SignRequest contains a password - this command should only be used on a trusted or secure connection
type SignRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UnsignedTransactions [][]byte               `protobuf:"bytes,1,rep,name=unsignedTransactions,proto3" json:"unsignedTransactions,omitempty"`
	Password             string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{23}
}

func (x *SignRequest) GetUnsignedTransactions() [][]byte {
	if x != nil {
		return x.UnsignedTransactions
	}
	return nil
}

func (x *SignRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SignedTransactions [][]byte               `protobuf:"bytes,1,rep,name=signedTransactions,proto3" json:"signedTransactions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{24}
}

func (x *SignResponse) GetSignedTransactions() [][]byte {
	if x != nil {
		return x.SignedTransactions
	}
	return nil
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{25}
}

type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{26}
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Foztor - lets try making auto compound more robust
type GetMempoolEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txid          string                 `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMempoolEntryRequest) Reset() {
	*x = GetMempoolEntryRequest{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMempoolEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMempoolEntryRequest) ProtoMessage() {}

func (x *GetMempoolEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMempoolEntryRequest.ProtoReflect.Descriptor instead.
func (*GetMempoolEntryRequest) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{27}
}

func (x *GetMempoolEntryRequest) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

type GetMempoolEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	IsOrphan      bool                   `protobuf:"varint,2,opt,name=is_orphan,json=isOrphan,proto3" json:"is_orphan,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // optional human-readable error (empty if none)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMempoolEntryResponse) Reset() {
	*x = GetMempoolEntryResponse{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMempoolEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMempoolEntryResponse) ProtoMessage() {}

func (x *GetMempoolEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMempoolEntryResponse.ProtoReflect.Descriptor instead.
func (*GetMempoolEntryResponse) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{28}
}

func (x *GetMempoolEntryResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetMempoolEntryResponse) GetIsOrphan() bool {
	if x != nil {
		return x.IsOrphan
	}
	return false
}

func (x *GetMempoolEntryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WaitForMempoolEntriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Txids []string               `protobuf:"bytes,1,rep,name=txids,proto3" json:"txids,omitempty"`
	// timeout in seconds to wait for all txids to appear in mempool/orphan pool
	TimeoutSeconds uint32 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WaitForMempoolEntriesRequest) Reset() {
	*x = WaitForMempoolEntriesRequest{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForMempoolEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForMempoolEntriesRequest) ProtoMessage() {}

func (x *WaitForMempoolEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForMempoolEntriesRequest.ProtoReflect.Descriptor instead.
func (*WaitForMempoolEntriesRequest) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{29}
}

func (x *WaitForMempoolEntriesRequest) GetTxids() []string {
	if x != nil {
		return x.Txids
	}
	return nil
}

func (x *WaitForMempoolEntriesRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type WaitForMempoolEntriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// true if all txids were observed before timeout
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// list of txids that were observed (subset, may be all)
	ObservedTxids []string `protobuf:"bytes,2,rep,name=observed_txids,json=observedTxids,proto3" json:"observed_txids,omitempty"`
	Error         string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForMempoolEntriesResponse) Reset() {
	*x = WaitForMempoolEntriesResponse{}
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForMempoolEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForMempoolEntriesResponse) ProtoMessage() {}

func (x *WaitForMempoolEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForMempoolEntriesResponse.ProtoReflect.Descriptor instead.
func (*WaitForMempoolEntriesResponse) Descriptor() ([]byte, []int) {
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP(), []int{30}
}

func (x *WaitForMempoolEntriesResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *WaitForMempoolEntriesResponse) GetObservedTxids() []string {
	if x != nil {
		return x.ObservedTxids
	}
	return nil
}

func (x *WaitForMempoolEntriesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_cmd_htnwallet_daemon_pb_htnwalletd_proto protoreflect.FileDescriptor

const file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDesc = "" +
	"\n" +
	"(cmd/htnwallet/daemon/pb/htnwalletd.proto\x12\n" +
	"htnwalletd\"\x13\n" +
	"\x11GetBalanceRequest\"\x93\x01\n" +
	"\x12GetBalanceResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\x04R\tavailable\x12\x18\n" +
	"\apending\x18\x02 \x01(\x04R\apending\x12E\n" +
	"\x0faddressBalances\x18\x03 \x03(\v2\x1b.htnwalletd.AddressBalancesR\x0faddressBalances\"c\n" +
	"\x0fAddressBalances\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\x04R\tavailable\x12\x18\n" +
	"\apending\x18\x03 \x01(\x04R\apending\"\x82\x02\n" +
	"!CreateUnsignedTransactionsRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12\x12\n" +
	"\x04from\x18\x03 \x03(\tR\x04from\x12:\n" +
	"\x18useExistingChangeAddress\x18\x04 \x01(\bR\x18useExistingChangeAddress\x12\x1c\n" +
	"\tisSendAll\x18\x05 \x01(\bR\tisSendAll\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x19\n" +
	"\x05limit\x18\a \x01(\tH\x00R\x05limit\x88\x01\x01B\b\n" +
	"\x06_limit\"X\n" +
	"\"CreateUnsignedTransactionsResponse\x122\n" +
	"\x14unsignedTransactions\x18\x01 \x03(\fR\x14unsignedTransactions\"\xb9\x01\n" +
	"(CreateUnsignedCompoundTransactionRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04from\x18\x02 \x03(\tR\x04from\x12:\n" +
	"\x18useExistingChangeAddress\x18\x03 \x01(\bR\x18useExistingChangeAddress\x12\x19\n" +
	"\x05limit\x18\x04 \x01(\tH\x00R\x05limit\x88\x01\x01B\b\n" +
	"\x06_limit\"_\n" +
	")CreateUnsignedCompoundTransactionResponse\x122\n" +
	"\x14unsignedTransactions\x18\x01 \x03(\fR\x14unsignedTransactions\"\x16\n" +
	"\x14ShowAddressesRequest\"1\n" +
	"\x15ShowAddressesResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x03(\tR\aaddress\"\x13\n" +
	"\x11NewAddressRequest\".\n" +
	"\x12NewAddressResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"t\n" +
	"\x10BroadcastRequest\x12\x1a\n" +
	"\bisDomain\x18\x01 \x01(\bR\bisDomain\x12\"\n" +
	"\ftransactions\x18\x02 \x03(\fR\ftransactions\x12 \n" +
	"\vallowOrphan\x18\x03 \x01(\bR\vallowOrphan\")\n" +
	"\x11BroadcastResponse\x12\x14\n" +
	"\x05txIDs\x18\x01 \x03(\tR\x05txIDs\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"F\n" +
	"\bOutpoint\x12$\n" +
	"\rtransactionId\x18\x01 \x01(\tR\rtransactionId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\"\x98\x01\n" +
	"\x15UtxosByAddressesEntry\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x120\n" +
	"\boutpoint\x18\x02 \x01(\v2\x14.htnwalletd.OutpointR\boutpoint\x123\n" +
	"\tutxoEntry\x18\x03 \x01(\v2\x15.htnwalletd.UtxoEntryR\tutxoEntry\"U\n" +
	"\x0fScriptPublicKey\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12(\n" +
	"\x0fscriptPublicKey\x18\x02 \x01(\tR\x0fscriptPublicKey\"\xb0\x01\n" +
	"\tUtxoEntry\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x04R\x06amount\x12E\n" +
	"\x0fscriptPublicKey\x18\x02 \x01(\v2\x1b.htnwalletd.ScriptPublicKeyR\x0fscriptPublicKey\x12$\n" +
	"\rblockDaaScore\x18\x03 \x01(\x04R\rblockDaaScore\x12\x1e\n" +
	"\n" +
	"isCoinbase\x18\x04 \x01(\bR\n" +
	"isCoinbase\"<\n" +
	" GetExternalSpendableUTXOsRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"`\n" +
	"!GetExternalSpendableUTXOsResponse\x12;\n" +
	"\aEntries\x18\x01 \x03(\v2!.htnwalletd.UtxosByAddressesEntryR\aEntries\"\xf2\x01\n" +
	"\vSendRequest\x12\x1c\n" +
	"\ttoAddress\x18\x01 \x01(\tR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04from\x18\x04 \x03(\tR\x04from\x12:\n" +
	"\x18useExistingChangeAddress\x18\x05 \x01(\bR\x18useExistingChangeAddress\x12\x1c\n" +
	"\tisSendAll\x18\x06 \x01(\bR\tisSendAll\x12\x19\n" +
	"\x05limit\x18\a \x01(\tH\x00R\x05limit\x88\x01\x01B\b\n" +
	"\x06_limit\"T\n" +
	"\fSendResponse\x12\x14\n" +
	"\x05txIDs\x18\x01 \x03(\tR\x05txIDs\x12.\n" +
	"\x12signedTransactions\x18\x02 \x03(\fR\x12signedTransactions\"]\n" +
	"\vSignRequest\x122\n" +
	"\x14unsignedTransactions\x18\x01 \x03(\fR\x14unsignedTransactions\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\">\n" +
	"\fSignResponse\x12.\n" +
	"\x12signedTransactions\x18\x01 \x03(\fR\x12signedTransactions\"\x13\n" +
	"\x11GetVersionRequest\".\n" +
	"\x12GetVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\",\n" +
	"\x16GetMempoolEntryRequest\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\tR\x04txid\"b\n" +
	"\x17GetMempoolEntryResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1b\n" +
	"\tis_orphan\x18\x02 \x01(\bR\bisOrphan\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"]\n" +
	"\x1cWaitForMempoolEntriesRequest\x12\x14\n" +
	"\x05txids\x18\x01 \x03(\tR\x05txids\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\rR\x0etimeoutSeconds\"l\n" +
	"\x1dWaitForMempoolEntriesResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12%\n" +
	"\x0eobserved_txids\x18\x02 \x03(\tR\robservedTxids\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xbe\t\n" +
	"\n" +
	"htnwalletd\x12M\n" +
	"\n" +
	"GetBalance\x12\x1d.htnwalletd.GetBalanceRequest\x1a\x1e.htnwalletd.GetBalanceResponse\"\x00\x12z\n" +
	"\x19GetExternalSpendableUTXOs\x12,.htnwalletd.GetExternalSpendableUTXOsRequest\x1a-.htnwalletd.GetExternalSpendableUTXOsResponse\"\x00\x12}\n" +
	"\x1aCreateUnsignedTransactions\x12-.htnwalletd.CreateUnsignedTransactionsRequest\x1a..htnwalletd.CreateUnsignedTransactionsResponse\"\x00\x12V\n" +
	"\rShowAddresses\x12 .htnwalletd.ShowAddressesRequest\x1a!.htnwalletd.ShowAddressesResponse\"\x00\x12M\n" +
	"\n" +
	"NewAddress\x12\x1d.htnwalletd.NewAddressRequest\x1a\x1e.htnwalletd.NewAddressResponse\"\x00\x12G\n" +
	"\bShutdown\x12\x1b.htnwalletd.ShutdownRequest\x1a\x1c.htnwalletd.ShutdownResponse\"\x00\x12J\n" +
	"\tBroadcast\x12\x1c.htnwalletd.BroadcastRequest\x1a\x1d.htnwalletd.BroadcastResponse\"\x00\x12;\n" +
	"\x04Send\x12\x17.htnwalletd.SendRequest\x1a\x18.htnwalletd.SendResponse\"\x00\x12;\n" +
	"\x04Sign\x12\x17.htnwalletd.SignRequest\x1a\x18.htnwalletd.SignResponse\"\x00\x12M\n" +
	"\n" +
	"GetVersion\x12\x1d.htnwalletd.GetVersionRequest\x1a\x1e.htnwalletd.GetVersionResponse\"\x00\x12\x92\x01\n" +
	"!CreateUnsignedCompoundTransaction\x124.htnwalletd.CreateUnsignedCompoundTransactionRequest\x1a5.htnwalletd.CreateUnsignedCompoundTransactionResponse\"\x00\x12\\\n" +
	"\x0fGetMempoolEntry\x12\".htnwalletd.GetMempoolEntryRequest\x1a#.htnwalletd.GetMempoolEntryResponse\"\x00\x12n\n" +
	"\x15WaitForMempoolEntries\x12(.htnwalletd.WaitForMempoolEntriesRequest\x1a).htnwalletd.WaitForMempoolEntriesResponse\"\x00B3Z1github.com/Hoosat-Oy/HTND/cmd/htnwallet/daemon/pbb\x06proto3"

var (
	file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescOnce sync.Once
	file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescData []byte
)

func file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescGZIP() []byte {
	file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescOnce.Do(func() {
		file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDesc), len(file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDesc)))
	})
	return file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDescData
}

var file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_cmd_htnwallet_daemon_pb_htnwalletd_proto_goTypes = []any{
	(*GetBalanceRequest)(nil),                         // 0: htnwalletd.GetBalanceRequest
	(*GetBalanceResponse)(nil),                        // 1: htnwalletd.GetBalanceResponse
	(*AddressBalances)(nil),                           // 2: htnwalletd.AddressBalances
	(*CreateUnsignedTransactionsRequest)(nil),         // 3: htnwalletd.CreateUnsignedTransactionsRequest
	(*CreateUnsignedTransactionsResponse)(nil),        // 4: htnwalletd.CreateUnsignedTransactionsResponse
	(*CreateUnsignedCompoundTransactionRequest)(nil),  // 5: htnwalletd.CreateUnsignedCompoundTransactionRequest
	(*CreateUnsignedCompoundTransactionResponse)(nil), // 6: htnwalletd.CreateUnsignedCompoundTransactionResponse
	(*ShowAddressesRequest)(nil),                      // 7: htnwalletd.ShowAddressesRequest
	(*ShowAddressesResponse)(nil),                     // 8: htnwalletd.ShowAddressesResponse
	(*NewAddressRequest)(nil),                         // 9: htnwalletd.NewAddressRequest
	(*NewAddressResponse)(nil),                        // 10: htnwalletd.NewAddressResponse
	(*BroadcastRequest)(nil),                          // 11: htnwalletd.BroadcastRequest
	(*BroadcastResponse)(nil),                         // 12: htnwalletd.BroadcastResponse
	(*ShutdownRequest)(nil),                           // 13: htnwalletd.ShutdownRequest
	(*ShutdownResponse)(nil),                          // 14: htnwalletd.ShutdownResponse
	(*Outpoint)(nil),                                  // 15: htnwalletd.Outpoint
	(*UtxosByAddressesEntry)(nil),                     // 16: htnwalletd.UtxosByAddressesEntry
	(*ScriptPublicKey)(nil),                           // 17: htnwalletd.ScriptPublicKey
	(*UtxoEntry)(nil),                                 // 18: htnwalletd.UtxoEntry
	(*GetExternalSpendableUTXOsRequest)(nil),          // 19: htnwalletd.GetExternalSpendableUTXOsRequest
	(*GetExternalSpendableUTXOsResponse)(nil),         // 20: htnwalletd.GetExternalSpendableUTXOsResponse
	(*SendRequest)(nil),                               // 21: htnwalletd.SendRequest
	(*SendResponse)(nil),                              // 22: htnwalletd.SendResponse
	(*SignRequest)(nil),                               // 23: htnwalletd.SignRequest
	(*SignResponse)(nil),                              // 24: htnwalletd.SignResponse
	(*GetVersionRequest)(nil),                         // 25: htnwalletd.GetVersionRequest
	(*GetVersionResponse)(nil),                        // 26: htnwalletd.GetVersionResponse
	(*GetMempoolEntryRequest)(nil),                    // 27: htnwalletd.GetMempoolEntryRequest
	(*GetMempoolEntryResponse)(nil),                   // 28: htnwalletd.GetMempoolEntryResponse
	(*WaitForMempoolEntriesRequest)(nil),              // 29: htnwalletd.WaitForMempoolEntriesRequest
	(*WaitForMempoolEntriesResponse)(nil),             // 30: htnwalletd.WaitForMempoolEntriesResponse
}
var file_cmd_htnwallet_daemon_pb_htnwalletd_proto_depIdxs = []int32{
	2,  // 0: htnwalletd.GetBalanceResponse.addressBalances:type_name -> htnwalletd.AddressBalances
	15, // 1: htnwalletd.UtxosByAddressesEntry.outpoint:type_name -> htnwalletd.Outpoint
	18, // 2: htnwalletd.UtxosByAddressesEntry.utxoEntry:type_name -> htnwalletd.UtxoEntry
	17, // 3: htnwalletd.UtxoEntry.scriptPublicKey:type_name -> htnwalletd.ScriptPublicKey
	16, // 4: htnwalletd.GetExternalSpendableUTXOsResponse.Entries:type_name -> htnwalletd.UtxosByAddressesEntry
	0,  // 5: htnwalletd.htnwalletd.GetBalance:input_type -> htnwalletd.GetBalanceRequest
	19, // 6: htnwalletd.htnwalletd.GetExternalSpendableUTXOs:input_type -> htnwalletd.GetExternalSpendableUTXOsRequest
	3,  // 7: htnwalletd.htnwalletd.CreateUnsignedTransactions:input_type -> htnwalletd.CreateUnsignedTransactionsRequest
	7,  // 8: htnwalletd.htnwalletd.ShowAddresses:input_type -> htnwalletd.ShowAddressesRequest
	9,  // 9: htnwalletd.htnwalletd.NewAddress:input_type -> htnwalletd.NewAddressRequest
	13, // 10: htnwalletd.htnwalletd.Shutdown:input_type -> htnwalletd.ShutdownRequest
	11, // 11: htnwalletd.htnwalletd.Broadcast:input_type -> htnwalletd.BroadcastRequest
	21, // 12: htnwalletd.htnwalletd.Send:input_type -> htnwalletd.SendRequest
	23, // 13: htnwalletd.htnwalletd.Sign:input_type -> htnwalletd.SignRequest
	25, // 14: htnwalletd.htnwalletd.GetVersion:input_type -> htnwalletd.GetVersionRequest
	5,  // 15: htnwalletd.htnwalletd.CreateUnsignedCompoundTransaction:input_type -> htnwalletd.CreateUnsignedCompoundTransactionRequest
	27, // 16: htnwalletd.htnwalletd.GetMempoolEntry:input_type -> htnwalletd.GetMempoolEntryRequest
	29, // 17: htnwalletd.htnwalletd.WaitForMempoolEntries:input_type -> htnwalletd.WaitForMempoolEntriesRequest
	1,  // 18: htnwalletd.htnwalletd.GetBalance:output_type -> htnwalletd.GetBalanceResponse
	20, // 19: htnwalletd.htnwalletd.GetExternalSpendableUTXOs:output_type -> htnwalletd.GetExternalSpendableUTXOsResponse
	4,  // 20: htnwalletd.htnwalletd.CreateUnsignedTransactions:output_type -> htnwalletd.CreateUnsignedTransactionsResponse
	8,  // 21: htnwalletd.htnwalletd.ShowAddresses:output_type -> htnwalletd.ShowAddressesResponse
	10, // 22: htnwalletd.htnwalletd.NewAddress:output_type -> htnwalletd.NewAddressResponse
	14, // 23: htnwalletd.htnwalletd.Shutdown:output_type -> htnwalletd.ShutdownResponse
	12, // 24: htnwalletd.htnwalletd.Broadcast:output_type -> htnwalletd.BroadcastResponse
	22, // 25: htnwalletd.htnwalletd.Send:output_type -> htnwalletd.SendResponse
	24, // 26: htnwalletd.htnwalletd.Sign:output_type -> htnwalletd.SignResponse
	26, // 27: htnwalletd.htnwalletd.GetVersion:output_type -> htnwalletd.GetVersionResponse
	6,  // 28: htnwalletd.htnwalletd.CreateUnsignedCompoundTransaction:output_type -> htnwalletd.CreateUnsignedCompoundTransactionResponse
	28, // 29: htnwalletd.htnwalletd.GetMempoolEntry:output_type -> htnwalletd.GetMempoolEntryResponse
	30, // 30: htnwalletd.htnwalletd.WaitForMempoolEntries:output_type -> htnwalletd.WaitForMempoolEntriesResponse
	18, // [18:31] is the sub-list for method output_type
	5,  // [5:18] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_cmd_htnwallet_daemon_pb_htnwalletd_proto_init() }
func file_cmd_htnwallet_daemon_pb_htnwalletd_proto_init() {
	if File_cmd_htnwallet_daemon_pb_htnwalletd_proto != nil {
		return
	}
	file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[3].OneofWrappers = []any{}
	file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[5].OneofWrappers = []any{}
	file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDesc), len(file_cmd_htnwallet_daemon_pb_htnwalletd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_htnwallet_daemon_pb_htnwalletd_proto_goTypes,
		DependencyIndexes: file_cmd_htnwallet_daemon_pb_htnwalletd_proto_depIdxs,
		MessageInfos:      file_cmd_htnwallet_daemon_pb_htnwalletd_proto_msgTypes,
	}.Build()
	File_cmd_htnwallet_daemon_pb_htnwalletd_proto = out.File
	file_cmd_htnwallet_daemon_pb_htnwalletd_proto_goTypes = nil
	file_cmd_htnwallet_daemon_pb_htnwalletd_proto_depIdxs = nil
}
